// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {tracker, keywords} from "./keywords.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(vQYQPOOOtQPO'#C|O|QPO'#C|O!RQPO'#C|O!WQPO'#C|OOQO'#Cr'#CrQYQPOOO!]QPO'#C}OOQO'#Cv'#CvQ!bQPOOO!gQPO,59hO#XQPO,59hO#aQPO,59hO#iQPO,59hO#qQPO,59hOOQO-E6p-E6pO#vQPO,59iOOQO-E6t-E6tO$XQPO1G/SO$^QPO'#CsO$iQPO1G/SO$qQPO1G/SOOQO'#Ct'#CtO$vQPO1G/SOOQO1G/S1G/SOOQO'#Cu'#CuO%OQPO1G/SO%WQPO1G/SO%]QPO'#DOO%kQPO1G/TO%|QPO'#DOOOQO'#Cw'#CwO&qQPO1G/TOOQO1G/T1G/TOOQO7+$n7+$nO'SQPO,59_OOQO-E6q-E6qO'XQPO7+$nO'^QPO7+$nOOQO-E6r-E6rOOQO-E6s-E6sO'cQPO7+$nO'hQPO,59jO%]QPO'#DOO'mQPO7+$oO'uQPO,59jOOQO'#Cx'#CxO'zQPO,59jOOQO-E6u-E6uOOQO7+$o7+$oOOQO1G.y1G.yO(oQPO<<HYOOQO<<HY<<HYOOQO1G/U1G/UO(tQPO<<HZOOQO-E6v-E6vOOQOAN=tAN=tO)VQPOAN=uOOQOAN=uAN=uOOQOG23aG23a",
  stateData: ")k~OoOS_OS~OPPOQQOTQOUQOVROWSOXVOZQO~OaYObZO~Ob[O~Ob]O~Ob^O~Oa`O~OXVO~OSbOPpaQpaTpaUpaVpaWpaXpaZpampa~OacOceO~OafOchO~OchOdiO~OakO~OYqO[nO]nObmOslO~OarO~OSsOagXcgX~OacOcuO~ORvO~OafOcrO~OcrOdiO~OayO~O[nO]nOb{OslO~O[nO]nOafOb{OslO~O^!OOa!OOd!OOe!OOYrX[rX]rXbrXsrXtrXcrX~OY!RO[nO]nOb{OslO~Oa!SO~OR!TO~Oa!UO~Oc!UO~Ot!VO~OafOc!WO~Oc!VO~O^!OOa!OOd!OOe!OOYra[ra]rabrasratracra~Oa!YO~OY![O[nO]nOb{OslO~OY!]O[nO]nOb{OslO~Oea~",
  goto: "#asPPPPPPPPPPPPPPPPPPPPPPtz!Q![!b!i!sPPP!y!}#SQUOR_UQdZRtdQg[Swg|R|mQj]RxjSXOURaXQp`S!Qp!ZR!Z!WQ!PnR!X!PTTOUVWOUXWo`p!W!ZQzlT}m{",
  nodeNames: "⚠ Import Export From As Globals Extensions Includes Breed To End Own Command Reporter Constant Comment Program Identifier OpenBracket CloseBracket String Number",
  maxTerm: 36,
  context: tracker,
  skippedNodes: [0,15],
  repeatNodeCount: 7,
  tokenData: "4c~RuX^#fpq#fqr$Zrs%qst$Ztu$Zuv$Zvw$Zwx$Zxy'jyz'oz{$Z{|$Z}!O't!O!P$Z!P!Q$Z!Q![2h![!]$Z!]!^3p!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z!}#O4X#P#Q4^#Q#R$Z#R#S$Z#T#o$Z#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~#kYo~X^#fpq#f#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~$`ea~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~%tVOr%qrs&Zs#O%q#O#P&`#P;'S%q;'S;=`'d<%lO%q~&`Od~~&cVOr%qrs&xs#O%q#O#P&`#P;'S%q;'S;=`'d<%lO%q~&}Vd~Or%qrs&Zs#O%q#O#P&`#P;'S%q;'S;=`'d<%lO%q~'gP;=`<%l%q~'oOs~~'tOt~~'yea~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![)[![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~)cge~a~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P*z!P!Q$Z!Q![)[![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y.Q#Y#o$Z~+Pea~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![,b![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~,ige~a~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![,b![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y.Q#Y#o$Z~.Vea~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|/h}!O/h!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~/mea~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![1O![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~1Vee~a~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![1O![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~2mRe~!O!P2v!Q![2h#X#Y3X~2yP!Q![2|~3RQe~!Q![2|#X#Y3X~3[Q{|3b}!O3b~3eP!Q![3h~3mPe~!Q![3h~3uS_~OY3pZ;'S3p;'S;=`4R<%lO3p~4UP;=`<%l3p~4^Ob~~4cOc~",
  tokenizers: [0],
  topRules: {"Program":[0,16]},
  specialized: [{term: 17, get: (value: any, stack: any) => (keywords(value, stack) << 1), external: keywords}],
  tokenPrec: 392
})
