// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {tracker, keywords} from "./keywords.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(WQYQPOOOtQPO'#C{O|QPO'#C{O!RQPO'#C{O!WQPO'#C{OOQO'#Cq'#CqQYQPOOO!]QPO'#C|OOQO'#Cu'#CuQ!bQPOOO!gQPO,59gO#XQPO,59gO#aQPO,59gO#iQPO,59gO#qQPO,59gOOQO-E6o-E6oO#vQPO,59hOOQO-E6s-E6sO$XQPO1G/RO$^QPO'#CrO$iQPO1G/ROOQO1G/R1G/ROOQO'#Cs'#CsO$qQPO1G/ROOQO'#Ct'#CtO$yQPO1G/RO%RQPO1G/RO%WQPO'#C}O%fQPO1G/SO%wQPO'#C}OOQO'#Cv'#CvO&lQPO1G/SOOQO1G/S1G/SOOQO7+$m7+$mO&}QPO,59^OOQO-E6p-E6pOOQO-E6q-E6qOOQO-E6r-E6rO'SQPO7+$mO'XQPO,59iO%WQPO'#C}O'^QPO7+$nO'fQPO,59iOOQO'#Cw'#CwO'kQPO,59iOOQO-E6t-E6tOOQO7+$n7+$nOOQO1G.x1G.xOOQO<<HX<<HXOOQO1G/T1G/TO(`QPO<<HYOOQO-E6u-E6uO(qQPOAN=tOOQOAN=tAN=tOOQOG23`G23`",
  stateData: ")V~OnOS^OS~OPPOQQOSQOTQOUROVSOWVOYQO~O`YOaZO~Oa[O~Oa]O~Oa^O~O``O~OWVO~ORbOPoaQoaSoaToaUoaVoaWoaYoaloa~O`cObeO~O`fObeO~ObeOchO~O`jO~OXpOZmO[mOalOrkO~O`qO~ORrO`fXbfX~O`cObqO~O`fObqO~ObqOchO~O`vO~OZmO[mOaxOrkO~OZmO[mO`fOaxOrkO~O]{O`{Oc{Od{OXqXZqX[qXaqXrqXsqXbqX~OX!OOZmO[mOaxOrkO~O`!PO~Ob!QO~Os!RO~O`fOb!SO~Ob!RO~O]{O`{Oc{Od{OXqaZqa[qaaqarqasqabqa~OX!VOZmO[mOaxOrkO~OX!WOZmO[mOaxOrkO~Od`~",
  goto: "#`rPPPPPPPPPPPPPPPPPPPPPsy!P!Z!a!h!rPPP!x!|#RQUOR_UQdZRsdQg[StgyRylQi]RuiSXOURaXQo`S}o!UR!U!SQ|mR!T|TTOUVWOUXWn`o!S!UQwkTzlx",
  nodeNames: "⚠ Import Export As Globals Extensions Includes Breed To End Own Command Reporter Constant Comment Program Identifier OpenBracket CloseBracket String Number",
  maxTerm: 35,
  context: tracker,
  skippedNodes: [0,14],
  repeatNodeCount: 7,
  tokenData: "4c~RuX^#fpq#fqr$Zrs%qst$Ztu$Zuv$Zvw$Zwx$Zxy'jyz'oz{$Z{|$Z}!O't!O!P$Z!P!Q$Z!Q![2h![!]$Z!]!^3p!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z!}#O4X#P#Q4^#Q#R$Z#R#S$Z#T#o$Z#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~#kYn~X^#fpq#f#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~$`e`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~%tVOr%qrs&Zs#O%q#O#P&`#P;'S%q;'S;=`'d<%lO%q~&`Oc~~&cVOr%qrs&xs#O%q#O#P&`#P;'S%q;'S;=`'d<%lO%q~&}Vc~Or%qrs&Zs#O%q#O#P&`#P;'S%q;'S;=`'d<%lO%q~'gP;=`<%l%q~'oOr~~'tOs~~'ye`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![)[![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~)cgd~`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P*z!P!Q$Z!Q![)[![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y.Q#Y#o$Z~+Pe`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![,b![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~,igd~`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![,b![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y.Q#Y#o$Z~.Ve`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|/h}!O/h!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~/me`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![1O![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~1Ved~`~qr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![1O![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~2mRd~!O!P2v!Q![2h#X#Y3X~2yP!Q![2|~3RQd~!Q![2|#X#Y3X~3[Q{|3b}!O3b~3eP!Q![3h~3mPd~!Q![3h~3uS^~OY3pZ;'S3p;'S;=`4R<%lO3p~4UP;=`<%l3p~4^Oa~~4cOb~",
  tokenizers: [0],
  topRules: {"Program":[0,15]},
  specialized: [{term: 16, get: (value: any, stack: any) => (keywords(value, stack) << 1), external: keywords}],
  tokenPrec: 372
})
