// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Globals = 1,
  Extensions = 2,
  Includes = 3,
  Breed = 4,
  To = 5,
  End = 6,
  Own = 7,
  Command = 8,
  Reporter = 9,
  Constant = 10,
  Comment = 11,
  Program = 12,
  OpenBracket = 13,
  Identifier = 14,
  CloseBracket = 15,
  String = 16,
  Number = 17
