// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {tracker, keywords} from "./keywords.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: ")lQYQPOOOwQPO'#DQO!PQPO'#DQO!UQPO'#DQO!ZQPO'#DQO!`QPO'#DQOOQO'#Cu'#CuQYQPOOO!eQQO'#DRO!jQSO'#DROOQO'#Cz'#CzQ!oQPOOO!wQPO,59lO#lQPO,59lO#tQPO,59lO#|QSO,59lO$UQPO,59lO$^QSO,59lOOQO-E6s-E6sO$cQPO,59mOOQO-E6x-E6xO$tQPO1G/WO$yQPO'#CvO%UQPO1G/WO%^QPO1G/WOOQO'#Cw'#CwO%cQPO1G/WOOQO1G/W1G/WOOQO'#Cx'#CxO%kQSO1G/WOOQO'#Cy'#CyO%sQPO1G/WO%{QSO1G/WO&QQPO'#DSO&`QPO1G/XO&qQPO'#DSOOQO'#C{'#C{O'fQPO1G/XOOQO1G/X1G/XOOQO7+$r7+$rO'wQPO,59bOOQO-E6t-E6tO'|QPO7+$rO(RQPO7+$rOOQO-E6u-E6uOOQO-E6v-E6vOOQO-E6w-E6wO(WQPO7+$rO(]QPO,59nO&QQPO'#DSO(bQPO7+$sO(jQPO,59nOOQO'#C|'#C|O(oQPO,59nOOQO-E6y-E6yOOQO7+$s7+$sOOQO1G.|1G.|O)dQPO<<H^OOQO<<H^<<H^OOQO1G/Y1G/YO)iQPO<<H_OOQO-E6z-E6zOOQOAN=xAN=xO)zQPOAN=yOOQOAN=yAN=yOOQOG23eG23e",
  stateData: "*`~OsOS`OS~OPPOQQOTROUQOVSOWTOXWOYXO[RO~Ob[Oc]O~Oc^O~Oc_O~Oc`O~OcaO~OgcO~OecO~OXWOYXO~OSeOPtaQtaTtaUtaVtaWtaXtaYta[taqta~ObfOdhO~ObiOdkO~OdkOelO~OdkOfnO~OepO~OZvO]sO^sOcrOwqO~ObwO~OSxObjXdjX~ObfOdzO~OR{O~ObiOdwO~OdwOelO~OdwOfnO~Oe!PO~O]sO^sOc!ROwqO~O]sO^sObiOc!ROwqO~O_!UOb!UOf!UOh!UOZvX]vX^vXcvXwvXxvXdvX~OZ!XO]sO^sOc!ROwqO~Ob!YO~OR!ZO~Ob![O~Od![O~Ox!]O~ObiOd!^O~Od!]O~O_!UOb!UOf!UOh!UOZva]va^vacvawvaxvadva~Ob!`O~OZ!bO]sO^sOc!ROwqO~OZ!cO]sO^sOc!ROwqO~Ohb~",
  goto: "#kwPPPPPPPPPPPPPPPPPPPPPPPPPx!O!U!`!f!l!s!}PPP#T#X#^QVORbVQg]RygQj^S|j!SR!SrQm_R}mQo`R!OoSZOVRdZQucS!Wu!aR!a!^Q!VsR!_!VTUOVVYOVZWtcu!^!aQ!QqT!Tr!R",
  nodeNames: "⚠ Import Export From As Globals Extensions Includes Breed To ToReport End Own Command Reporter Constant Comment Program Identifier OpenBracket CloseBracket AlwaysReporter String AlwaysCommand Number",
  maxTerm: 40,
  context: tracker,
  skippedNodes: [0,16],
  repeatNodeCount: 8,
  tokenData: "5y~RuX^#fpq#fqr$Zrs%ust$Ztu$Zuv$Zvw$Zwx$Zxy(dyz(iz{$Z{|$Z}!O(n!O!P$Z!P!Q$Z!Q![4O![!]$Z!]!^5W!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z!}#O5o#P#Q5t#Q#R$Z#R#S$Z#T#o$Z#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~#kYs~X^#fpq#f#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#fV$degQeSbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~%xZOY%uYZ&kZr%urs&ks#O%u#O#P&p#P;'S%u;'S;=`(^<%l~%u~O%u~~&k~&pOf~~&sZOY%uYZ&kZr%urs'fs#O%u#O#P&p#P;'S%u;'S;=`(^<%l~%u~O%u~~&k~'kZf~OY%uYZ&kZr%urs&ks#O%u#O#P&p#P;'S%u;'S;=`(^<%l~%u~O%u~~&k~(aP;=`<%l%u~(iOw~~(nOx~V(wegQeSbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![*Y![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$ZV*eggQeShPbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P+|!P!Q$Z!Q![*Y![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y/[#Y#o$ZV,VegQeSbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![-h![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$ZV-sggQeShPbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![-h![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y/[#Y#o$ZV/eegQeSbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|0v}!O0v!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$ZV1PegQeSbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![2b![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$ZV2megQeShPbPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![2b![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$ZP4TRhP!O!P4^!Q![4O#X#Y4oP4aP!Q![4dP4iQhP!Q![4d#X#Y4oP4rQ{|4x}!O4xP4{P!Q![5OP5TPhP!Q![5O~5]S`~OY5WZ;'S5W;'S;=`5i<%lO5W~5lP;=`<%l5W~5tOc~~5yOd~",
  tokenizers: [0, 1, 2],
  topRules: {"Program":[0,17]},
  specialized: [{term: 18, get: (value: any, stack: any) => (keywords(value, stack) << 1), external: keywords}],
  tokenPrec: 427
})
